apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.stable.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
    {{- with .Values.stable }}
      containers:
      - name: {{ .containerName }}
        image: "{{ .image }}:{{ .imageTag }}"
        imagePullPolicy: {{ .containerSpecImagePullPolicy }}
        command: ["vite", "dev"]
        args:
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "{{ .port | toString }}"
        resources:
          requests:
            memory: {{ .resources.requestsMemory }}
            cpu: {{ .resources.requestsCpu }}
          limits:
            memory: {{ .resources.limitsMemory }}
            cpu: {{ .resources.limitsCpu }}
        ports:
        - containerPort: {{ .port }}
          name: http
  {{- end }}